### ISSUE TITLE
Scenario 1 - 1

### ISSUE THREAD

**Issue by pablotdv** [Nit123/Exam-98-361-Prep#1]
In your Scenario 1 - 1 you define the discount to ` if (quantity >= 100)` is 20%, but in the Decision Table we are not have this condition.

Why you create this condition in your method?

Please, see my solution https://github.com/pablotdv/MTA-98-361/blob/master/Lesson01/Scenario01/Program.cs

**Comment by Nit123** [comment]
On the last row, the final column (condition) is N. This means, given the logic of the table, that it is highly likely that a quantity equal or greater than 100 will be discounted 20%. The reason I added it in my program is for completeness. Your program is equally correct, but I put the final condition in mine to ensure that if the user accidently put a quantity over/equal to 100, the program doesn't freak out.

**Comment by pablotdv** [comment]
Thanks for your explanation. I will try the test for the certification of MTA 98-361. Mainly for test my English and second test my knowledge in C#.
